name: MyItem
author: BeeAZ
api: 4.0.0
version: 0.0.2
main: BeeAZ\MyItem\Main
softdepend: ["PiggyCustomEnchants"]

commands: 
  mi:
    description: Upgrade , Enhance , Store Item 
    permission: myitem.edit
permissions:
  myitem.edit:
    default: op
