name: MyItem
author: BeeAZ
api: 5.0.0
version: 1.0.1
main: BeeAZ\MyItem\Main

commands: 
  mi:
    description: Upgrade , Enhance , Store Item 
    permission: myitem.edit
permissions:
  myitem.edit:
    default: op
